<a href="https://colab.research.google.com/github/msamunetogetoge/masamune/blob/master/laplace_logistic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ラプラス近似の為の勾配法の作成

In [0]:
import numpy as np
import seaborn as sns

In [0]:
from scipy.special import expit as sigmoid
def likelifood(w,w_0,S,t,x):
    w_1 = w-w_0
    y=sigmoid(np.dot(w.T , x)).reshape(-1,)
    lf = -1/2 * np.dot(np.dot(w_1.T , np.linalg.inv(S)) ,w_1) +np.sum(t*np.log(y) +(1-t)*np.log(1-y))
    return lf

In [0]:
class SGD():
    def __init__(self,w_0, S_0,x,t,rate,th):
        self.r=rate
        self.w_0 =w_0
        self.S_0=S_0
        self.x=x
        self.t=t
        self.th =th
    def diff(self,w):
        Nd = -np.dot((w-self.w_0).T,np.linalg.inv(self.S_0.T))
        Br=np.dot(t.T-sigmoid(np.dot(w.T,self.x)),self.x.T)
        d=Nd+Br
        d=d.reshape(-1,1)
        return d
    def learn(self,N):
        self.w=self.w_0
        for i in range(N):
            self.d=self.diff(self.w)
            self.w_new =self.w-self.r*self.d
            lf_new = likelifood(self.w_new,self.w_0,self.S_0,self.t,self.x)
            lf_old = likelifood(self.w,self.w_0,self.S_0,self.t,self.x)
            c = (lf_new - lf_old)/lf_old
            self.w =self.w_new
            self.lf=lf_new
            print("End iteration of {}".format(i+1))
            if np.abs(c)<self.th:
                print("Convergence!! itr={}".format(i+1))
                break
        print("End the learning")
        return self.w_new
        

In [0]:
SG.diff(w_0)

array([[16.3,  5.1, 32.3, 17.5]])

# データの準備

In [0]:
import pandas as pd
from sklearn import datasets

iris = datasets.load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['target'] = iris.target_names[iris.target]
df.head()

sepal length (cm)  sepal width (cm)  ...  petal width (cm)  target
0                5.1               3.5  ...               0.2  setosa
1                4.9               3.0  ...               0.2  setosa
2                4.7               3.2  ...               0.2  setosa
3                4.6               3.1  ...               0.2  setosa
4                5.0               3.6  ...               0.2  setosa

[5 rows x 5 columns]

In [0]:
df.target.unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [0]:
data =df.target=="setosa"
df_reg_index = df[data].index
df_reg=df.drop(index=df_reg_index)
df_reg.head()

sepal length (cm)  sepal width (cm)  ...  petal width (cm)      target
50                7.0               3.2  ...               1.4  versicolor
51                6.4               3.2  ...               1.5  versicolor
52                6.9               3.1  ...               1.5  versicolor
53                5.5               2.3  ...               1.3  versicolor
54                6.5               2.8  ...               1.5  versicolor

[5 rows x 5 columns]

In [0]:
y=df_reg.target
x=df_reg.drop(columns="target")

stats = x.describe().T
def norm(x):
  return (x - stats['mean']) /stats['std']

m=len(x.columns)
w_0 =np.zeros((m,1))
S=np.eye(m)

x=norm(x).T
#x=x.T

In [0]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder()
encoded = oe.fit_transform(np.array(y).reshape(-1,1))
t=encoded

# ベイズロジスティック回帰

In [0]:
SG=SGD(w_0=w_0, S_0=S, x=x, t=t, rate=0.0001,th=0.00001)
w_new=SG.learn(10000)

End iteration of 1
End iteration of 2
End iteration of 3
End iteration of 4
End iteration of 5
End iteration of 6
End iteration of 7
End iteration of 8
End iteration of 9
End iteration of 10
End iteration of 11
End iteration of 12
End iteration of 13
End iteration of 14
End iteration of 15
End iteration of 16
End iteration of 17
End iteration of 18
End iteration of 19
End iteration of 20
End iteration of 21
End iteration of 22
End iteration of 23
End iteration of 24
End iteration of 25
End iteration of 26
End iteration of 27
End iteration of 28
End iteration of 29
End iteration of 30
End iteration of 31
End iteration of 32
End iteration of 33
End iteration of 34
End iteration of 35
End iteration of 36
End iteration of 37
End iteration of 38
End iteration of 39
End iteration of 40
End iteration of 41
End iteration of 42
End iteration of 43
End iteration of 44
End iteration of 45
End iteration of 46
End iteration of 47
End iteration of 48
End iteration of 49
End iteration of 50
End itera

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in log
  
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in multiply
  


ストリーミング出力は最後の 5000 行に切り捨てられました。
End iteration of 5003
End iteration of 5004
End iteration of 5005
End iteration of 5006
End iteration of 5007
End iteration of 5008
End iteration of 5009
End iteration of 5010
End iteration of 5011
End iteration of 5012
End iteration of 5013
End iteration of 5014
End iteration of 5015
End iteration of 5016
End iteration of 5017
End iteration of 5018
End iteration of 5019
End iteration of 5020
End iteration of 5021
End iteration of 5022
End iteration of 5023
End iteration of 5024
End iteration of 5025
End iteration of 5026
End iteration of 5027
End iteration of 5028
End iteration of 5029
End iteration of 5030
End iteration of 5031
End iteration of 5032
End iteration of 5033
End iteration of 5034
End iteration of 5035
End iteration of 5036
End iteration of 5037
End iteration of 5038
End iteration of 5039
End iteration of 5040
End iteration of 5041
End iteration of 5042
End iteration of 5043
End iteration of 5044
End iteration of 5045
End iteration of 5046


In [0]:
y=sigmoid(np.dot(w_new.T , x))
S=-np.linalg.inv(S)+ np.sum(y*(1-y)*np.dot(x.T, x))

In [50]:
from sklearn.metrics import confusion_matrix
w_s =np.random.multivariate_normal(w_new.reshape(-1,), S,5)
for i in w_s :
    y= sigmoid(np.dot(i , x))
    pred=[]
    for i in range(max(y.shape)):
        pred.append(np.argmax([y[i], 1-y[i]]))
    cm = confusion_matrix(t, pred)
    print(cm)

[[44  6]
 [ 9 41]]
[[44  6]
 [ 9 41]]
[[44  6]
 [ 6 44]]
[[44  6]
 [ 9 41]]
[[44  6]
 [ 9 41]]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: covariance is not positive-semidefinite.
  


In [0]:
y = sigmoid(np.dot(w_new.T , x)).reshape(-1,)
t_pred =[]
for i in range(len(y)):
        t_pred.append(np.argmax([y[i], 1-y[i]]))
cm = confusion_matrix(t, t_pred)
print(cm)

[[44  6]
 [ 9 41]]


80%くらいの正解率

In [0]:
from sklearn.linear_model import LogisticRegression
x=df_reg.drop(columns="target")
lr=LogisticRegression()
lr.fit(x,t)
t_pred=lr.predict(x)
cm=confusion_matrix(t,t_pred)
print(cm)

[[47  3]
 [ 1 49]]


/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


sklearn のロジスティック回帰では95%くらい

In [0]:
print(w_new)
print(lr.coef_)

[[-1256766.3429386 ]
 [ -919580.86868426]
 [-1666362.41275086]
 [-1742105.97530117]]
[[-0.39443136 -0.51327025  2.93075043  2.4170433 ]]
